/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::IoTAnalytics::Channel
 */
export interface AwsIotanalyticsChannel {
  ChannelStorage?: ChannelStorage;
  ChannelName?: string;
  Id?: string;
  RetentionPeriod?: RetentionPeriod;
  Tags?: Tag[];
}
export interface ChannelStorage {
  ServiceManagedS3?: ServiceManagedS3;
  CustomerManagedS3?: CustomerManagedS3;
}
export interface ServiceManagedS3 {}
export interface CustomerManagedS3 {
  Bucket: string;
  RoleArn: string;
  KeyPrefix?: string;
}
export interface RetentionPeriod {
  NumberOfDays?: number;
  Unlimited?: boolean;
}
export interface Tag {
  Value: string;
  Key: string;
}
