/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Events::Connection.
 */
export interface AwsEventsConnection {
  /**
   * Name of the connection.
   */
  Name?: string;
  /**
   * The arn of the connection resource.
   */
  Arn?: string;
  /**
   * The arn of the secrets manager secret created in the customer account.
   */
  SecretArn?: string;
  /**
   * Description of the connection.
   */
  Description?: string;
  AuthorizationType: "API_KEY" | "BASIC" | "OAUTH_CLIENT_CREDENTIALS";
  AuthParameters: {
    [k: string]: unknown;
  };
}
