/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Budgets::Budget
 */
export interface AwsBudgetsBudget {
  Id?: string;
  NotificationsWithSubscribers?: NotificationWithSubscribers[];
  Budget: BudgetData;
}
export interface NotificationWithSubscribers {
  Subscribers: Subscriber[];
  Notification: Notification;
}
export interface Subscriber {
  SubscriptionType: string;
  Address: string;
}
export interface Notification {
  ComparisonOperator: string;
  NotificationType: string;
  Threshold: number;
  ThresholdType?: string;
}
export interface BudgetData {
  BudgetLimit?: Spend;
  TimePeriod?: TimePeriod;
  TimeUnit: string;
  PlannedBudgetLimits?: {
    [k: string]: unknown;
  };
  CostFilters?: {
    [k: string]: unknown;
  };
  BudgetName?: string;
  CostTypes?: CostTypes;
  BudgetType: string;
}
export interface Spend {
  Amount: number;
  Unit: string;
}
export interface TimePeriod {
  Start?: string;
  End?: string;
}
export interface CostTypes {
  IncludeSupport?: boolean;
  IncludeOtherSubscription?: boolean;
  IncludeTax?: boolean;
  IncludeSubscription?: boolean;
  UseBlended?: boolean;
  IncludeUpfront?: boolean;
  IncludeDiscount?: boolean;
  IncludeCredit?: boolean;
  IncludeRecurring?: boolean;
  UseAmortized?: boolean;
  IncludeRefund?: boolean;
}
