/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ElastiCache::UserGroup
 */
export interface AwsElasticacheUsergroup {
  /**
   * Indicates user group status. Can be "creating", "active", "modifying", "deleting".
   */
  Status?: string;
  /**
   * The ID of the user group.
   */
  UserGroupId: string;
  /**
   * Must be redis.
   */
  Engine: "redis";
  /**
   * List of users associated to this user group.
   */
  UserIds?: string[];
  /**
   * The Amazon Resource Name (ARN) of the user account.
   */
  Arn?: string;
}
