/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An AWS account ID.
 */
export type AccountId = string;
/**
 * An Organizational Unit ID.
 */
export type OrganizationalUnitId = string;
/**
 * An AWS resource type
 */
export type ResourceType = string;
/**
 * A resource ARN.
 */
export type ResourceArn = string;

/**
 * Creates an AWS Firewall Manager policy.
 */
export interface AwsFmsPolicy {
  ExcludeMap?: IEMap;
  ExcludeResourceTags: boolean;
  IncludeMap?: IEMap;
  Id?: string;
  PolicyName: string;
  RemediationEnabled: boolean;
  ResourceTags?:
    | []
    | [ResourceTag]
    | [ResourceTag, ResourceTag]
    | [ResourceTag, ResourceTag, ResourceTag]
    | [ResourceTag, ResourceTag, ResourceTag, ResourceTag]
    | [ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag]
    | [ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag]
    | [ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag]
    | [ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag, ResourceTag];
  ResourceType: ResourceType;
  ResourceTypeList?: ResourceType[];
  SecurityServicePolicyData: {
    ManagedServiceData?: string;
    Type:
      | "WAF"
      | "WAFV2"
      | "SHIELD_ADVANCED"
      | "SECURITY_GROUPS_COMMON"
      | "SECURITY_GROUPS_CONTENT_AUDIT"
      | "SECURITY_GROUPS_USAGE_AUDIT"
      | "NETWORK_FIREWALL"
      | "DNS_FIREWALL";
  };
  Arn?: ResourceArn;
  DeleteAllPolicyResources?: boolean;
  ResourcesCleanUp?: boolean;
  Tags?: PolicyTag[];
}
/**
 * An FMS includeMap or excludeMap.
 */
export interface IEMap {
  ACCOUNT?: AccountId[];
  ORGUNIT?: OrganizationalUnitId[];
}
/**
 * A resource tag.
 */
export interface ResourceTag {
  Key: string;
  Value?: string;
}
/**
 * A policy tag.
 */
export interface PolicyTag {
  Key: string;
  Value: string;
}
