/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::CodeDeploy::DeploymentConfig
 */
export interface AwsCodedeployDeploymentconfig {
  DeploymentConfigName?: string;
  Id?: string;
  TrafficRoutingConfig?: TrafficRoutingConfig;
  ComputePlatform?: string;
  MinimumHealthyHosts?: MinimumHealthyHosts;
}
export interface TrafficRoutingConfig {
  Type: string;
  TimeBasedLinear?: TimeBasedLinear;
  TimeBasedCanary?: TimeBasedCanary;
}
export interface TimeBasedLinear {
  LinearInterval: number;
  LinearPercentage: number;
}
export interface TimeBasedCanary {
  CanaryPercentage: number;
  CanaryInterval: number;
}
export interface MinimumHealthyHosts {
  Value: number;
  Type: string;
}
