/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::RDS::DBInstance
 */
export interface AwsRdsDbinstance {
  StorageEncrypted?: boolean;
  Timezone?: string;
  Port?: string;
  DBClusterIdentifier?: string;
  MonitoringInterval?: number;
  DBParameterGroupName?: string;
  MultiAZ?: boolean;
  Engine?: string;
  Tags?: Tag[];
  EndpointAddress?: string;
  PerformanceInsightsKMSKeyId?: string;
  SourceDBInstanceIdentifier?: string;
  EngineVersion?: string;
  StorageType?: string;
  KmsKeyId?: string;
  DBInstanceClass: string;
  DeleteAutomatedBackups?: boolean;
  PerformanceInsightsRetentionPeriod?: number;
  AvailabilityZone?: string;
  OptionGroupName?: string;
  EnablePerformanceInsights?: boolean;
  AutoMinorVersionUpgrade?: boolean;
  DBSubnetGroupName?: string;
  DeletionProtection?: boolean;
  DBInstanceIdentifier?: string;
  AllocatedStorage?: string;
  MasterUserPassword?: string;
  DBSecurityGroups?: string[];
  MasterUsername?: string;
  MaxAllocatedStorage?: number;
  PromotionTier?: number;
  PubliclyAccessible?: boolean;
  Id?: string;
  Domain?: string;
  CharacterSetName?: string;
  MonitoringRoleArn?: string;
  EndpointPort?: string;
  AssociatedRoles?: DBInstanceRole[];
  ProcessorFeatures?: ProcessorFeature[];
  PreferredBackupWindow?: string;
  CopyTagsToSnapshot?: boolean;
  DomainIAMRoleName?: string;
  LicenseModel?: string;
  PreferredMaintenanceWindow?: string;
  Iops?: number;
  SourceRegion?: string;
  CACertificateIdentifier?: string;
  VPCSecurityGroups?: string[];
  AllowMajorVersionUpgrade?: boolean;
  DBName?: string;
  EnableIAMDatabaseAuthentication?: boolean;
  BackupRetentionPeriod?: number;
  DBSnapshotIdentifier?: string;
  EnableCloudwatchLogsExports?: string[];
  UseDefaultProcessorFeatures?: boolean;
}
export interface Tag {
  Value: string;
  Key: string;
}
export interface DBInstanceRole {
  RoleArn: string;
  FeatureName: string;
}
export interface ProcessorFeature {
  Value?: string;
  Name?: string;
}
