/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The Amazon Resource Name (ARN) of the License Manager configuration.
 */
export type LicenseConfigurationArn = string;

/**
 * Resource schema for AWS::ImageBuilder::DistributionConfiguration
 */
export interface AwsImagebuilderDistributionconfiguration {
  /**
   * The Amazon Resource Name (ARN) of the distribution configuration.
   */
  Arn?: string;
  /**
   * The name of the distribution configuration.
   */
  Name: string;
  /**
   * The description of the distribution configuration.
   */
  Description?: string;
  /**
   * The distributions of the distribution configuration.
   */
  Distributions: Distribution[];
  /**
   * The tags associated with the component.
   */
  Tags?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".{1,}".
     */
    [k: string]: string;
  };
}
/**
 * The distributions of the distribution configuration.
 */
export interface Distribution {
  /**
   * region
   */
  Region: string;
  /**
   * The specific AMI settings (for example, launch permissions, AMI tags).
   */
  AmiDistributionConfiguration?: {
    /**
     * The name of the AMI distribution configuration.
     */
    Name?: string;
    /**
     * The KMS key identifier used to encrypt the distributed image.
     */
    KmsKeyId?: string;
    /**
     * The description of the AMI distribution configuration.
     */
    Description?: string;
    /**
     * The tags to apply to AMIs distributed to this Region.
     */
    AmiTags?: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` ".{1,}".
       */
      [k: string]: string;
    };
    /**
     * The ID of accounts to which you want to distribute an image.
     */
    TargetAccountIds?: string[];
    /**
     * Launch permissions can be used to configure which AWS accounts can use the AMI to launch instances.
     */
    LaunchPermissionConfiguration?: {
      /**
       * The AWS account ID.
       */
      UserIds?: string[];
      /**
       * The name of the group.
       */
      UserGroups?: string[];
      /**
       * The ARN for an Amazon Web Services Organization that you want to share your AMI with.
       */
      OrganizationArns?: string[];
      /**
       * The ARN for an Organizations organizational unit (OU) that you want to share your AMI with.
       */
      OrganizationalUnitArns?: string[];
    };
  };
  /**
   * Container distribution settings for encryption, licensing, and sharing in a specific Region.
   */
  ContainerDistributionConfiguration?: {
    /**
     * The description of the container distribution configuration.
     */
    Description?: string;
    /**
     * Tags that are attached to the container distribution configuration.
     */
    ContainerTags?: string[];
    /**
     * The destination repository for the container distribution configuration.
     */
    TargetRepository?: {
      /**
       * The service of target container repository.
       */
      Service?: "ECR";
      /**
       * The repository name of target container repository.
       */
      RepositoryName?: string;
    };
  };
  /**
   * The License Manager Configuration to associate with the AMI in the specified Region.
   */
  LicenseConfigurationArns?: LicenseConfigurationArn[];
  /**
   * A group of launchTemplateConfiguration settings that apply to image distribution.
   */
  LaunchTemplateConfigurations?: LaunchTemplateConfiguration[];
}
/**
 * launchTemplateConfiguration settings that apply to image distribution.
 */
export interface LaunchTemplateConfiguration {
  /**
   * Identifies the EC2 launch template to use.
   */
  LaunchTemplateId?: string;
  /**
   * The account ID that this configuration applies to.
   */
  AccountId?: string;
  /**
   * Set the specified EC2 launch template as the default launch template for the specified account.
   */
  SetDefaultVersion?: boolean;
}
