/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::DynamoDB::Table
 */
export interface AwsDynamodbTable {
  SSESpecification?: SSESpecification;
  KinesisStreamSpecification?: KinesisStreamSpecification;
  ContributorInsightsSpecification?: ContributorInsightsSpecification;
  StreamSpecification?: StreamSpecification;
  PointInTimeRecoverySpecification?: PointInTimeRecoverySpecification;
  ProvisionedThroughput?: ProvisionedThroughput;
  TableName?: string;
  AttributeDefinitions?: AttributeDefinition[];
  BillingMode?: string;
  GlobalSecondaryIndexes?: GlobalSecondaryIndex[];
  KeySchema: KeySchema[];
  LocalSecondaryIndexes?: LocalSecondaryIndex[];
  Id?: string;
  Arn?: string;
  StreamArn?: string;
  TableClass?: string;
  Tags?: Tag[];
  TimeToLiveSpecification?: TimeToLiveSpecification;
}
export interface SSESpecification {
  KMSMasterKeyId?: string;
  SSEEnabled: boolean;
  SSEType?: string;
}
export interface KinesisStreamSpecification {
  StreamArn: string;
}
export interface ContributorInsightsSpecification {
  Enabled: boolean;
}
export interface StreamSpecification {
  StreamViewType: string;
}
export interface PointInTimeRecoverySpecification {
  PointInTimeRecoveryEnabled?: boolean;
}
export interface ProvisionedThroughput {
  WriteCapacityUnits: number;
  ReadCapacityUnits: number;
}
export interface AttributeDefinition {
  AttributeType: string;
  AttributeName: string;
}
export interface GlobalSecondaryIndex {
  IndexName: string;
  Projection: Projection;
  ProvisionedThroughput?: ProvisionedThroughput;
  KeySchema: KeySchema[];
  ContributorInsightsSpecification?: ContributorInsightsSpecification;
}
export interface Projection {
  ProjectionType?: string;
  NonKeyAttributes?: string[];
}
export interface KeySchema {
  KeyType: string;
  AttributeName: string;
}
export interface LocalSecondaryIndex {
  IndexName: string;
  Projection: Projection;
  KeySchema: KeySchema[];
}
export interface Tag {
  Value: string;
  Key: string;
}
export interface TimeToLiveSpecification {
  Enabled: boolean;
  AttributeName: string;
}
