/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IpAddress = string;
export type Protocol = "tcp" | "udp";
export type Port = number;

/**
 * Resource schema for AWS::EC2::NetworkInsightsPath
 */
export interface AwsEc2Networkinsightspath {
  NetworkInsightsPathId?: string;
  NetworkInsightsPathArn?: string;
  CreatedDate?: string;
  SourceIp?: IpAddress;
  DestinationIp?: IpAddress;
  Source: string;
  Destination: string;
  Protocol: Protocol;
  DestinationPort?: Port;
  Tags?: Tag[];
}
export interface Tag {
  Key: string;
  Value?: string;
}
