/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::RDS::DBClusterParameterGroup
 */
export interface AwsRdsDbclusterparametergroup {
  Id?: string;
  Description: string;
  Family: string;
  Parameters: {
    [k: string]: unknown;
  };
  Tags?: Tag[];
}
export interface Tag {
  Key: string;
  Value: string;
}
