/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SageMaker::Domain
 */
export interface AwsSagemakerDomain {
  /**
   * The Amazon Resource Name (ARN) of the created domain.
   */
  DomainArn?: string;
  /**
   * The URL to the created domain.
   */
  Url?: string;
  /**
   * Specifies the VPC used for non-EFS traffic. The default value is PublicInternetOnly.
   */
  AppNetworkAccessType?: "PublicInternetOnly" | "VpcOnly";
  /**
   * The mode of authentication that members use to access the domain.
   */
  AuthMode: "SSO" | "IAM";
  /**
   * The default user settings.
   */
  DefaultUserSettings: {
    /**
     * The user profile Amazon Resource Name (ARN).
     */
    ExecutionRole?: string;
    /**
     * The Jupyter server's app settings.
     */
    JupyterServerAppSettings?: {
      DefaultResourceSpec?: ResourceSpec;
    };
    /**
     * The kernel gateway app settings.
     */
    KernelGatewayAppSettings?: {
      /**
       * A list of custom SageMaker images that are configured to run as a KernelGateway app.
       */
      CustomImages?:
        | []
        | [CustomImage]
        | [CustomImage, CustomImage]
        | [CustomImage, CustomImage, CustomImage]
        | [CustomImage, CustomImage, CustomImage, CustomImage]
        | [CustomImage, CustomImage, CustomImage, CustomImage, CustomImage]
        | [CustomImage, CustomImage, CustomImage, CustomImage, CustomImage, CustomImage]
        | [CustomImage, CustomImage, CustomImage, CustomImage, CustomImage, CustomImage, CustomImage]
        | [CustomImage, CustomImage, CustomImage, CustomImage, CustomImage, CustomImage, CustomImage, CustomImage]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ]
        | [
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage,
            CustomImage
          ];
      /**
       * The default instance type and the Amazon Resource Name (ARN) of the default SageMaker image used by the KernelGateway app.
       */
      DefaultResourceSpec?: {
        /**
         * The instance type that the image version runs on.
         */
        InstanceType?:
          | "system"
          | "ml.t3.micro"
          | "ml.t3.small"
          | "ml.t3.medium"
          | "ml.t3.large"
          | "ml.t3.xlarge"
          | "ml.t3.2xlarge"
          | "ml.m5.large"
          | "ml.m5.xlarge"
          | "ml.m5.2xlarge"
          | "ml.m5.4xlarge"
          | "ml.m5.8xlarge"
          | "ml.m5.12xlarge"
          | "ml.m5.16xlarge"
          | "ml.m5.24xlarge"
          | "ml.c5.large"
          | "ml.c5.xlarge"
          | "ml.c5.2xlarge"
          | "ml.c5.4xlarge"
          | "ml.c5.9xlarge"
          | "ml.c5.12xlarge"
          | "ml.c5.18xlarge"
          | "ml.c5.24xlarge"
          | "ml.p3.2xlarge"
          | "ml.p3.8xlarge"
          | "ml.p3.16xlarge"
          | "ml.g4dn.xlarge"
          | "ml.g4dn.2xlarge"
          | "ml.g4dn.4xlarge"
          | "ml.g4dn.8xlarge"
          | "ml.g4dn.12xlarge"
          | "ml.g4dn.16xlarge";
        /**
         * The ARN of the SageMaker image that the image version belongs to.
         */
        SageMakerImageArn?: string;
        /**
         * The ARN of the image version created on the instance.
         */
        SageMakerImageVersionArn?: string;
      };
    };
    /**
     * The security groups for the Amazon Virtual Private Cloud (VPC) that Studio uses for communication.
     */
    SecurityGroups?:
      | []
      | [string]
      | [string, string]
      | [string, string, string]
      | [string, string, string, string]
      | [string, string, string, string, string];
    /**
     * The sharing settings.
     */
    SharingSettings?: {
      /**
       * Whether to include the notebook cell output when sharing the notebook. The default is Disabled.
       */
      NotebookOutputOption?: "Allowed" | "Disabled";
      /**
       * When NotebookOutputOption is Allowed, the AWS Key Management Service (KMS) encryption key ID used to encrypt the notebook cell output in the Amazon S3 bucket.
       */
      S3KmsKeyId?: string;
      /**
       * When NotebookOutputOption is Allowed, the Amazon S3 bucket used to store the shared notebook snapshots.
       */
      S3OutputPath?: string;
    };
  };
  /**
   * A name for the domain.
   */
  DomainName: string;
  /**
   * SageMaker uses AWS KMS to encrypt the EFS volume attached to the domain with an AWS managed customer master key (CMK) by default.
   */
  KmsKeyId?: string;
  /**
   * The VPC subnets that Studio uses for communication.
   */
  SubnetIds:
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  /**
   * A list of tags to apply to the user profile.
   */
  Tags?:
    | []
    | [Tag]
    | [Tag, Tag]
    | [Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag, Tag]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ]
    | [
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag,
        Tag
      ];
  /**
   * The ID of the Amazon Virtual Private Cloud (VPC) that Studio uses for communication.
   */
  VpcId: string;
  /**
   * The domain name.
   */
  DomainId?: string;
  /**
   * The ID of the Amazon Elastic File System (EFS) managed by this Domain.
   */
  HomeEfsFileSystemId?: string;
  /**
   * The SSO managed application instance ID.
   */
  SingleSignOnManagedApplicationInstanceId?: string;
}
export interface ResourceSpec {
  /**
   * The instance type that the image version runs on.
   */
  InstanceType?:
    | "system"
    | "ml.t3.micro"
    | "ml.t3.small"
    | "ml.t3.medium"
    | "ml.t3.large"
    | "ml.t3.xlarge"
    | "ml.t3.2xlarge"
    | "ml.m5.large"
    | "ml.m5.xlarge"
    | "ml.m5.2xlarge"
    | "ml.m5.4xlarge"
    | "ml.m5.8xlarge"
    | "ml.m5.12xlarge"
    | "ml.m5.16xlarge"
    | "ml.m5.24xlarge"
    | "ml.c5.large"
    | "ml.c5.xlarge"
    | "ml.c5.2xlarge"
    | "ml.c5.4xlarge"
    | "ml.c5.9xlarge"
    | "ml.c5.12xlarge"
    | "ml.c5.18xlarge"
    | "ml.c5.24xlarge"
    | "ml.p3.2xlarge"
    | "ml.p3.8xlarge"
    | "ml.p3.16xlarge"
    | "ml.g4dn.xlarge"
    | "ml.g4dn.2xlarge"
    | "ml.g4dn.4xlarge"
    | "ml.g4dn.8xlarge"
    | "ml.g4dn.12xlarge"
    | "ml.g4dn.16xlarge";
  /**
   * The ARN of the SageMaker image that the image version belongs to.
   */
  SageMakerImageArn?: string;
  /**
   * The ARN of the image version created on the instance.
   */
  SageMakerImageVersionArn?: string;
}
/**
 * A custom SageMaker image.
 */
export interface CustomImage {
  /**
   * The Name of the AppImageConfig.
   */
  AppImageConfigName: string;
  /**
   * The name of the CustomImage. Must be unique to your account.
   */
  ImageName: string;
  /**
   * The version number of the CustomImage.
   */
  ImageVersionNumber?: number;
}
export interface Tag {
  Value: string;
  Key: string;
}
