/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource schema for AWS::ImageBuilder::ImagePipeline
 */
export type AwsImagebuilderImagepipeline = {
  /**
   * The Amazon Resource Name (ARN) of the image pipeline.
   */
  Arn?: string;
  /**
   * The name of the image pipeline.
   */
  Name?: string;
  /**
   * The description of the image pipeline.
   */
  Description?: string;
  /**
   * The image tests configuration of the image pipeline.
   */
  ImageTestsConfiguration?: {
    /**
     * Defines if tests should be executed when building this image.
     */
    ImageTestsEnabled?: boolean;
    /**
     * The maximum time in minutes that tests are permitted to run.
     */
    TimeoutMinutes?: number;
  };
  /**
   * The status of the image pipeline.
   */
  Status?: "DISABLED" | "ENABLED";
  /**
   * The schedule of the image pipeline.
   */
  Schedule?: {
    /**
     * The expression determines how often EC2 Image Builder evaluates your pipelineExecutionStartCondition.
     */
    ScheduleExpression?: string;
    /**
     * The condition configures when the pipeline should trigger a new image build.
     */
    PipelineExecutionStartCondition?: "EXPRESSION_MATCH_ONLY" | "EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE";
  };
  /**
   * The Amazon Resource Name (ARN) of the image recipe that defines how images are configured, tested, and assessed.
   */
  ImageRecipeArn?: string;
  /**
   * The Amazon Resource Name (ARN) of the container recipe that defines how images are configured and tested.
   */
  ContainerRecipeArn?: string;
  /**
   * The Amazon Resource Name (ARN) of the distribution configuration associated with this image pipeline.
   */
  DistributionConfigurationArn?: string;
  /**
   * The Amazon Resource Name (ARN) of the infrastructure configuration associated with this image pipeline.
   */
  InfrastructureConfigurationArn?: string;
  /**
   * Collects additional information about the image being created, including the operating system (OS) version and package list.
   */
  EnhancedImageMetadataEnabled?: boolean;
  /**
   * The tags of this image pipeline.
   */
  Tags?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".{1,}".
     */
    [k: string]: string;
  };
} & {
  [k: string]: unknown;
};
