/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SortDirection = "ASC" | "DESC";

/**
 * Definition of AWS::AmplifyUIBuilder::Component Resource Type
 */
export interface AwsAmplifyuibuilderComponent {
  AppId?: string;
  BindingProperties?: ComponentBindingProperties;
  Children?: ComponentChild[];
  CollectionProperties?: ComponentCollectionProperties;
  ComponentType?: string;
  CreatedAt?: string;
  EnvironmentName?: string;
  Id?: string;
  ModifiedAt?: string;
  Name?: string;
  Overrides?: ComponentOverrides;
  Properties?: ComponentProperties;
  SourceId?: string;
  Tags?: Tags;
  Variants?: ComponentVariant[];
}
export interface ComponentBindingProperties {
  [k: string]: ComponentBindingPropertiesValue;
}
/**
 * This interface was referenced by `ComponentBindingProperties`'s JSON-Schema definition
 * via the `patternProperty` ".+".
 */
export interface ComponentBindingPropertiesValue {
  DefaultValue?: string;
  Type?: string;
  BindingProperties?: ComponentBindingPropertiesValueProperties;
}
export interface ComponentBindingPropertiesValueProperties {
  Field?: string;
  DefaultValue?: string;
  Bucket?: string;
  UserAttribute?: string;
  Model?: string;
  Predicates?: Predicate[];
  Key?: string;
}
export interface Predicate {
  Operator?: string;
  Field?: string;
  Or?: Predicate[];
  And?: Predicate[];
  Operand?: string;
}
export interface ComponentChild {
  ComponentType: string;
  Children?: ComponentChild[];
  Properties: ComponentProperties;
  Name: string;
}
export interface ComponentProperties {
  [k: string]: ComponentProperty;
}
/**
 * This interface was referenced by `ComponentProperties`'s JSON-Schema definition
 * via the `patternProperty` ".+".
 */
export interface ComponentProperty {
  Condition?: ComponentConditionProperty;
  UserAttribute?: string;
  ImportedValue?: string;
  BindingProperties?: ComponentPropertyBindingProperties;
  Bindings?: FormBindings;
  Configured?: boolean;
  Concat?: ComponentProperty[];
  DefaultValue?: string;
  Type?: string;
  Value?: string;
  Model?: string;
  CollectionBindingProperties?: ComponentPropertyBindingProperties;
  Event?: string;
}
export interface ComponentConditionProperty {
  Operator?: string;
  Field?: string;
  Operand?: string;
  Else?: ComponentProperty;
  Then?: ComponentProperty;
  Property?: string;
}
export interface ComponentPropertyBindingProperties {
  Field?: string;
  Property: string;
}
export interface FormBindings {
  [k: string]: FormBindingElement;
}
/**
 * This interface was referenced by `FormBindings`'s JSON-Schema definition
 * via the `patternProperty` ".+".
 */
export interface FormBindingElement {
  Element: string;
  Property: string;
}
export interface ComponentCollectionProperties {
  [k: string]: ComponentDataConfiguration;
}
/**
 * This interface was referenced by `ComponentCollectionProperties`'s JSON-Schema definition
 * via the `patternProperty` ".+".
 */
export interface ComponentDataConfiguration {
  Model: string;
  Sort?: SortProperty[];
  Identifiers?: string[];
  Predicate?: Predicate;
}
export interface SortProperty {
  Field: string;
  Direction: SortDirection;
}
export interface ComponentOverrides {
  [k: string]: ComponentOverridesValue;
}
/**
 * This interface was referenced by `ComponentOverrides`'s JSON-Schema definition
 * via the `patternProperty` ".+".
 */
export interface ComponentOverridesValue {
  /**
   * This interface was referenced by `ComponentOverridesValue`'s JSON-Schema definition
   * via the `patternProperty` ".+".
   */
  [k: string]: string;
}
export interface Tags {
  /**
   * This interface was referenced by `Tags`'s JSON-Schema definition
   * via the `patternProperty` "^(?!aws:)[a-zA-Z+-=._:/]+$".
   */
  [k: string]: string;
}
export interface ComponentVariant {
  VariantValues?: ComponentVariantValues;
  Overrides?: ComponentOverrides;
}
export interface ComponentVariantValues {
  /**
   * This interface was referenced by `ComponentVariantValues`'s JSON-Schema definition
   * via the `patternProperty` ".+".
   */
  [k: string]: string;
}
