/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ServiceCatalog::CloudFormationProduct
 */
export interface AwsServicecatalogCloudformationproduct {
  Owner: string;
  Description?: string;
  ProductName?: string;
  SupportEmail?: string;
  ProvisioningArtifactNames?: string;
  Name: string;
  ReplaceProvisioningArtifacts?: boolean;
  SupportDescription?: string;
  Distributor?: string;
  ProvisioningArtifactIds?: string;
  AcceptLanguage?: string;
  SupportUrl?: string;
  Id?: string;
  Tags?: Tag[];
  ProvisioningArtifactParameters: ProvisioningArtifactProperties[];
}
export interface Tag {
  Value: string;
  Key: string;
}
export interface ProvisioningArtifactProperties {
  Description?: string;
  Info: {
    [k: string]: unknown;
  };
  DisableTemplateValidation?: boolean;
  Name?: string;
}
