/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ApiGateway::DocumentationPart
 */
export interface AwsApigatewayDocumentationpart {
  Id?: string;
  Location: Location;
  Properties: string;
  RestApiId: string;
}
export interface Location {
  Method?: string;
  Name?: string;
  Path?: string;
  StatusCode?: string;
  Type?: string;
}
