/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ElasticBeanstalk::ConfigurationTemplate
 */
export interface AwsElasticbeanstalkConfigurationtemplate {
  Id?: string;
  ApplicationName: string;
  Description?: string;
  EnvironmentId?: string;
  OptionSettings?: ConfigurationOptionSetting[];
  PlatformArn?: string;
  SolutionStackName?: string;
  SourceConfiguration?: SourceConfiguration;
}
export interface ConfigurationOptionSetting {
  Namespace: string;
  OptionName: string;
  ResourceName?: string;
  Value?: string;
}
export interface SourceConfiguration {
  ApplicationName: string;
  TemplateName: string;
}
