/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type KnowledgeBaseType = "EXTERNAL" | "CUSTOM";
export type SourceConfiguration = {
  [k: string]: unknown;
};

/**
 * Definition of AWS::Wisdom::KnowledgeBase Resource Type
 */
export interface AwsWisdomKnowledgebase {
  Description?: string;
  KnowledgeBaseArn?: string;
  KnowledgeBaseId?: string;
  KnowledgeBaseType: KnowledgeBaseType;
  Name: string;
  RenderingConfiguration?: RenderingConfiguration;
  ServerSideEncryptionConfiguration?: ServerSideEncryptionConfiguration;
  SourceConfiguration?: SourceConfiguration;
  Tags?: Tag[];
}
export interface RenderingConfiguration {
  TemplateUri?: string;
}
export interface ServerSideEncryptionConfiguration {
  KmsKeyId?: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
