/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Route53Resolver::ResolverEndpoint
 */
export interface AwsRoute53ResolverResolverendpoint {
  ResolverEndpointId?: string;
  IpAddressCount?: string;
  Arn?: string;
  Direction: string;
  HostVPCId?: string;
  Name?: string;
  IpAddresses: IpAddressRequest[];
  SecurityGroupIds: string[];
  Tags?: Tag[];
}
export interface IpAddressRequest {
  Ip?: string;
  SubnetId: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
