/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Specifies lifecycle rules for an Amazon S3Outposts bucket. You must specify at least one of the following: AbortIncompleteMultipartUpload, ExpirationDate, ExpirationInDays.
 */
export type Rule =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };

/**
 * Resource Type Definition for AWS::S3Outposts::Bucket
 */
export interface AwsS3OutpostsBucket {
  /**
   * The Amazon Resource Name (ARN) of the specified bucket.
   */
  Arn?: string;
  /**
   * A name for the bucket.
   */
  BucketName: string;
  /**
   * The id of the customer outpost on which the bucket resides.
   */
  OutpostId: string;
  /**
   * An arbitrary set of tags (key-value pairs) for this S3Outposts bucket.
   */
  Tags?: Tag[];
  /**
   * Rules that define how Amazon S3Outposts manages objects during their lifetime.
   */
  LifecycleConfiguration?: {
    /**
     * A list of lifecycle rules for individual objects in an Amazon S3Outposts bucket.
     */
    Rules: Rule[];
  };
}
export interface Tag {
  Key: string;
  Value: string;
}
