/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Lambda::Permission
 */
export interface AwsLambdaPermission {
  Id?: string;
  Action: string;
  EventSourceToken?: string;
  FunctionName: string;
  Principal: string;
  SourceAccount?: string;
  SourceArn?: string;
}
