/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::VPCCidrBlock
 */
export interface AwsEc2Vpccidrblock {
  CidrBlock?: string;
  Ipv6Pool?: string;
  Id?: string;
  VpcId: string;
  Ipv6CidrBlock?: string;
  AmazonProvidedIpv6CidrBlock?: boolean;
}
