/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Batch::ComputeEnvironment
 */
export interface AwsBatchComputeenvironment {
  UnmanagedvCpus?: number;
  Type: string;
  ServiceRole?: string;
  ComputeEnvironmentName?: string;
  ComputeResources?: ComputeResources;
  State?: string;
  Id?: string;
  Tags?: {
    [k: string]: unknown;
  };
}
export interface ComputeResources {
  SpotIamFleetRole?: string;
  MaxvCpus: number;
  Ec2Configuration?: Ec2ConfigurationObject[];
  BidPercentage?: number;
  SecurityGroupIds?: string[];
  Subnets: string[];
  Type: string;
  AllocationStrategy?: string;
  MinvCpus?: number;
  LaunchTemplate?: LaunchTemplateSpecification;
  ImageId?: string;
  InstanceRole?: string;
  InstanceTypes?: string[];
  Ec2KeyPair?: string;
  PlacementGroup?: string;
  Tags?: {
    [k: string]: unknown;
  };
  DesiredvCpus?: number;
}
export interface Ec2ConfigurationObject {
  ImageIdOverride?: string;
  ImageType: string;
}
export interface LaunchTemplateSpecification {
  LaunchTemplateName?: string;
  LaunchTemplateId?: string;
  Version?: string;
}
