/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource schema for AWS::SES::ConfigurationSet.
 */
export interface AwsSesConfigurationset {
  /**
   * The name of the configuration set.
   */
  Name?: string;
}
