/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::DataPipeline::Pipeline
 */
export interface AwsDatapipelinePipeline {
  PipelineTags?: PipelineTag[];
  ParameterObjects: ParameterObject[];
  Description?: string;
  Activate?: boolean;
  PipelineObjects?: PipelineObject[];
  Id?: string;
  ParameterValues?: ParameterValue[];
  Name: string;
}
export interface PipelineTag {
  Value: string;
  Key: string;
}
export interface ParameterObject {
  Attributes: ParameterAttribute[];
  Id: string;
}
export interface ParameterAttribute {
  StringValue: string;
  Key: string;
}
export interface PipelineObject {
  Fields: Field[];
  Id: string;
  Name: string;
}
export interface Field {
  RefValue?: string;
  StringValue?: string;
  Key: string;
}
export interface ParameterValue {
  StringValue: string;
  Id: string;
}
