/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::AppSync::Resolver
 */
export interface AwsAppsyncResolver {
  TypeName: string;
  PipelineConfig?: PipelineConfig;
  RequestMappingTemplate?: string;
  ResponseMappingTemplate?: string;
  MaxBatchSize?: number;
  ResolverArn?: string;
  SyncConfig?: SyncConfig;
  ResponseMappingTemplateS3Location?: string;
  DataSourceName?: string;
  Kind?: string;
  CachingConfig?: CachingConfig;
  Id?: string;
  RequestMappingTemplateS3Location?: string;
  FieldName: string;
  ApiId: string;
}
export interface PipelineConfig {
  Functions?: string[];
}
export interface SyncConfig {
  ConflictHandler?: string;
  ConflictDetection: string;
  LambdaConflictHandlerConfig?: LambdaConflictHandlerConfig;
}
export interface LambdaConflictHandlerConfig {
  LambdaConflictHandlerArn?: string;
}
export interface CachingConfig {
  CachingKeys?: string[];
  Ttl: number;
}
