/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This resource schema represents the NotificationChannel resource in the Amazon DevOps Guru.
 */
export interface AwsDevopsguruNotificationchannel {
  Config: NotificationChannelConfig;
  /**
   * The ID of a notification channel.
   */
  Id?: string;
}
/**
 * Information about notification channels you have configured with DevOps Guru.
 */
export interface NotificationChannelConfig {
  Sns?: SnsChannelConfig;
}
/**
 * Information about a notification channel configured in DevOps Guru to send notifications when insights are created.
 */
export interface SnsChannelConfig {
  TopicArn?: string;
}
