/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::GuardDuty::Filter
 */
export interface AwsGuarddutyFilter {
  Action: string;
  Description: string;
  DetectorId: string;
  FindingCriteria: FindingCriteria;
  Rank: number;
  Id?: string;
  Name: string;
}
export interface FindingCriteria {
  Criterion?: {
    [k: string]: unknown;
  };
  ItemType?: Condition;
}
export interface Condition {
  Lt?: number;
  Gte?: number;
  Neq?: string[];
  Eq?: string[];
  Lte?: number;
}
