/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::EIP
 */
export interface AwsEc2Eip {
  PublicIpv4Pool?: string;
  Id?: string;
  Domain?: string;
  InstanceId?: string;
  Tags?: Tag[];
  AllocationId?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
