/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Subscription ARN
 */
export type Arn = string;

/**
 * AWS Cost Anomaly Detection leverages advanced Machine Learning technologies to identify anomalous spend and root causes, so you can quickly take action. Create subscription to be notified
 */
export interface AwsCeAnomalysubscription {
  SubscriptionArn?: Arn;
  /**
   * The name of the subscription.
   */
  SubscriptionName: string;
  /**
   * The accountId
   */
  AccountId?: string;
  /**
   * A list of cost anomaly monitors.
   */
  MonitorArnList: Arn[];
  /**
   * A list of subscriber
   */
  Subscribers: Subscriber[];
  /**
   * The dollar value that triggers a notification if the threshold is exceeded.
   */
  Threshold: number;
  /**
   * The frequency at which anomaly reports are sent over email.
   */
  Frequency: "DAILY" | "IMMEDIATE" | "WEEKLY";
}
export interface Subscriber {
  Address: string;
  Status?: "CONFIRMED" | "DECLINED";
  Type: "EMAIL" | "SNS";
}
