/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An Amazon Resource Name (ARN) of an IAM role that AWS Elemental MediaPackage will assume when accessing the key provider service.
 */
export type RoleArn = string;
/**
 * An optional string to include in the name of the manifest.
 */
export type ManifestName = string;
/**
 * Duration (in seconds) of each fragment. Actual fragments will be rounded to the nearest multiple of the source fragment duration.
 */
export type SegmentDurationSeconds = number;

/**
 * Resource schema for AWS::MediaPackage::PackagingConfiguration
 */
export interface AwsMediapackagePackagingconfiguration {
  /**
   * The ID of the PackagingConfiguration.
   */
  Id: string;
  /**
   * The ID of a PackagingGroup.
   */
  PackagingGroupId: string;
  /**
   * The ARN of the PackagingConfiguration.
   */
  Arn?: string;
  /**
   * A CMAF packaging configuration.
   */
  CmafPackage?: {
    Encryption?: CmafEncryption;
    /**
     * A list of HLS manifest configurations.
     */
    HlsManifests: HlsManifest[];
    SegmentDurationSeconds?: SegmentDurationSeconds;
    /**
     * When includeEncoderConfigurationInSegments is set to true, MediaPackage places your encoder's Sequence Parameter Set (SPS), Picture Parameter Set (PPS), and Video Parameter Set (VPS) metadata in every video segment instead of in the init fragment. This lets you use different SPS/PPS/VPS settings for your assets during content playback.
     */
    IncludeEncoderConfigurationInSegments?: boolean;
  };
  /**
   * A Dynamic Adaptive Streaming over HTTP (DASH) packaging configuration.
   */
  DashPackage?: {
    /**
     * A list of DASH manifest configurations.
     */
    DashManifests: DashManifest[];
    Encryption?: DashEncryption;
    /**
     * A list of triggers that controls when the outgoing Dynamic Adaptive Streaming over HTTP (DASH) Media Presentation Description (MPD) will be partitioned into multiple periods. If empty, the content will not be partitioned into more than one period. If the list contains "ADS", new periods will be created where the Asset contains SCTE-35 ad markers.
     */
    PeriodTriggers?: "ADS"[];
    SegmentDurationSeconds?: SegmentDurationSeconds;
    /**
     * Determines the type of SegmentTemplate included in the Media Presentation Description (MPD). When set to NUMBER_WITH_TIMELINE, a full timeline is presented in each SegmentTemplate, with $Number$ media URLs. When set to TIME_WITH_TIMELINE, a full timeline is presented in each SegmentTemplate, with $Time$ media URLs. When set to NUMBER_WITH_DURATION, only a duration is included in each SegmentTemplate, with $Number$ media URLs.
     */
    SegmentTemplateFormat?: "NUMBER_WITH_TIMELINE" | "TIME_WITH_TIMELINE" | "NUMBER_WITH_DURATION";
    /**
     * When includeEncoderConfigurationInSegments is set to true, MediaPackage places your encoder's Sequence Parameter Set (SPS), Picture Parameter Set (PPS), and Video Parameter Set (VPS) metadata in every video segment instead of in the init fragment. This lets you use different SPS/PPS/VPS settings for your assets during content playback.
     */
    IncludeEncoderConfigurationInSegments?: boolean;
  };
  /**
   * An HTTP Live Streaming (HLS) packaging configuration.
   */
  HlsPackage?: {
    Encryption?: HlsEncryption;
    /**
     * A list of HLS manifest configurations.
     */
    HlsManifests: HlsManifest[];
    SegmentDurationSeconds?: SegmentDurationSeconds;
    /**
     * When enabled, audio streams will be placed in rendition groups in the output.
     */
    UseAudioRenditionGroup?: boolean;
  };
  /**
   * A Microsoft Smooth Streaming (MSS) PackagingConfiguration.
   */
  MssPackage?: {
    Encryption?: MssEncryption;
    /**
     * A list of MSS manifest configurations.
     */
    MssManifests: MssManifest[];
    SegmentDurationSeconds?: SegmentDurationSeconds;
  };
  /**
   * A collection of tags associated with a resource
   */
  Tags?: Tag[];
}
/**
 * A CMAF encryption configuration.
 */
export interface CmafEncryption {
  SpekeKeyProvider: SpekeKeyProvider;
}
/**
 * A configuration for accessing an external Secure Packager and Encoder Key Exchange (SPEKE) service that will provide encryption keys.
 */
export interface SpekeKeyProvider {
  RoleArn: RoleArn;
  /**
   * The system IDs to include in key requests.
   */
  SystemIds: string[];
  /**
   * The URL of the external key provider service.
   */
  Url: string;
}
/**
 * An HTTP Live Streaming (HLS) manifest configuration.
 */
export interface HlsManifest {
  /**
   * This setting controls how ad markers are included in the packaged OriginEndpoint. "NONE" will omit all SCTE-35 ad markers from the output. "PASSTHROUGH" causes the manifest to contain a copy of the SCTE-35 ad markers (comments) taken directly from the input HTTP Live Streaming (HLS) manifest. "SCTE35_ENHANCED" generates ad markers and blackout tags based on SCTE-35 messages in the input source.
   */
  AdMarkers?: "NONE" | "SCTE35_ENHANCED" | "PASSTHROUGH";
  /**
   * When enabled, an I-Frame only stream will be included in the output.
   */
  IncludeIframeOnlyStream?: boolean;
  ManifestName?: ManifestName;
  /**
   * The interval (in seconds) between each EXT-X-PROGRAM-DATE-TIME tag inserted into manifests. Additionally, when an interval is specified ID3Timed Metadata messages will be generated every 5 seconds using the ingest time of the content. If the interval is not specified, or set to 0, then no EXT-X-PROGRAM-DATE-TIME tags will be inserted into manifests and no ID3Timed Metadata messages will be generated. Note that irrespective of this parameter, if any ID3 Timed Metadata is found in HTTP Live Streaming (HLS) input, it will be passed through to HLS output.
   */
  ProgramDateTimeIntervalSeconds?: number;
  /**
   * When enabled, the EXT-X-KEY tag will be repeated in output manifests.
   */
  RepeatExtXKey?: boolean;
  StreamSelection?: StreamSelection;
}
/**
 * A StreamSelection configuration.
 */
export interface StreamSelection {
  /**
   * The maximum video bitrate (bps) to include in output.
   */
  MaxVideoBitsPerSecond?: number;
  /**
   * The minimum video bitrate (bps) to include in output.
   */
  MinVideoBitsPerSecond?: number;
  /**
   * A directive that determines the order of streams in the output.
   */
  StreamOrder?: "ORIGINAL" | "VIDEO_BITRATE_ASCENDING" | "VIDEO_BITRATE_DESCENDING";
}
/**
 * A DASH manifest configuration.
 */
export interface DashManifest {
  /**
   * Determines the position of some tags in the Media Presentation Description (MPD). When set to FULL, elements like SegmentTemplate and ContentProtection are included in each Representation. When set to COMPACT, duplicate elements are combined and presented at the AdaptationSet level.
   */
  ManifestLayout?: "FULL" | "COMPACT";
  ManifestName?: ManifestName;
  /**
   * Minimum duration (in seconds) that a player will buffer media before starting the presentation.
   */
  MinBufferTimeSeconds?: number;
  /**
   * The Dynamic Adaptive Streaming over HTTP (DASH) profile type. When set to "HBBTV_1_5", HbbTV 1.5 compliant output is enabled.
   */
  Profile?: "NONE" | "HBBTV_1_5";
  StreamSelection?: StreamSelection;
}
/**
 * A Dynamic Adaptive Streaming over HTTP (DASH) encryption configuration.
 */
export interface DashEncryption {
  SpekeKeyProvider: SpekeKeyProvider;
}
/**
 * An HTTP Live Streaming (HLS) encryption configuration.
 */
export interface HlsEncryption {
  /**
   * An HTTP Live Streaming (HLS) encryption configuration.
   */
  ConstantInitializationVector?: string;
  /**
   * The encryption method to use.
   */
  EncryptionMethod?: "AES_128" | "SAMPLE_AES";
  SpekeKeyProvider: SpekeKeyProvider;
}
/**
 * A CMAF encryption configuration.
 */
export interface MssEncryption {
  SpekeKeyProvider: SpekeKeyProvider;
}
/**
 * A Microsoft Smooth Streaming (MSS) manifest configuration.
 */
export interface MssManifest {
  ManifestName?: ManifestName;
  StreamSelection?: StreamSelection;
}
export interface Tag {
  Key: string;
  Value: string;
}
