/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::VPCPeeringConnection
 */
export interface AwsEc2Vpcpeeringconnection {
  Id?: string;
  PeerOwnerId?: string;
  PeerRegion?: string;
  PeerRoleArn?: string;
  PeerVpcId: string;
  Tags?: Tag[];
  VpcId: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
