/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SNS::Topic
 */
export interface AwsSnsTopic {
  KmsMasterKeyId?: string;
  DisplayName?: string;
  FifoTopic?: boolean;
  ContentBasedDeduplication?: boolean;
  Id?: string;
  Subscription?: Subscription[];
  Tags?: Tag[];
  TopicName?: string;
}
export interface Subscription {
  Endpoint: string;
  Protocol: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
