/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Batch::JobQueue
 */
export interface AwsBatchJobqueue {
  ComputeEnvironmentOrder: ComputeEnvironmentOrder[];
  Priority: number;
  State?: string;
  SchedulingPolicyArn?: string;
  Id?: string;
  JobQueueName?: string;
  Tags?: {
    [k: string]: unknown;
  };
}
export interface ComputeEnvironmentOrder {
  ComputeEnvironment: string;
  Order: number;
}
