/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::VPNConnection
 */
export interface AwsEc2Vpnconnection {
  Id?: string;
  CustomerGatewayId: string;
  StaticRoutesOnly?: boolean;
  Tags?: Tag[];
  TransitGatewayId?: string;
  Type: string;
  VpnGatewayId?: string;
  VpnTunnelOptionsSpecifications?: VpnTunnelOptionsSpecification[];
}
export interface Tag {
  Key: string;
  Value: string;
}
export interface VpnTunnelOptionsSpecification {
  PreSharedKey?: string;
  TunnelInsideCidr?: string;
}
