/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::RDS::OptionGroup
 */
export interface AwsRdsOptiongroup {
  Id?: string;
  EngineName: string;
  MajorEngineVersion: string;
  OptionConfigurations: OptionConfiguration[];
  OptionGroupDescription: string;
  Tags?: Tag[];
}
export interface OptionConfiguration {
  DBSecurityGroupMemberships?: string[];
  OptionName: string;
  OptionSettings?: OptionSetting[];
  OptionVersion?: string;
  Port?: number;
  VpcSecurityGroupMemberships?: string[];
}
export interface OptionSetting {
  Name?: string;
  Value?: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
