/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The contacts or contact methods that the escalation plan or engagement plan is engaging.
 */
export type Targets =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };

/**
 * Resource Type definition for AWS::SSMContacts::Contact
 */
export interface AwsSsmcontactsContact {
  /**
   * Alias of the contact. String value with 20 to 256 characters. Only alphabetical, numeric characters, dash, or underscore allowed.
   */
  Alias: string;
  /**
   * Name of the contact. String value with 3 to 256 characters. Only alphabetical, space, numeric characters, dash, or underscore allowed.
   */
  DisplayName: string;
  /**
   * Contact type, which specify type of contact. Currently supported values: “PERSONAL”, “SHARED”, “OTHER“.
   */
  Type: "PERSONAL" | "CUSTOM" | "SERVICE" | "ESCALATION";
  /**
   * The stages that an escalation plan or engagement plan engages contacts and contact methods in.
   */
  Plan: Stage[];
  /**
   * The Amazon Resource Name (ARN) of the contact.
   */
  Arn?: string;
}
/**
 * A set amount of time that an escalation plan or engagement plan engages the specified contacts or contact methods.
 */
export interface Stage {
  /**
   * The time to wait until beginning the next stage.
   */
  DurationInMinutes: number;
  /**
   * The contacts or contact methods that the escalation plan or engagement plan is engaging.
   */
  Targets?: Targets[];
}
