/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SES::ConfigurationSetEventDestination
 */
export interface AwsSesConfigurationseteventdestination {
  Id?: string;
  ConfigurationSetName: string;
  EventDestination: EventDestination;
}
export interface EventDestination {
  CloudWatchDestination?: CloudWatchDestination;
  Enabled?: boolean;
  MatchingEventTypes: string[];
  Name?: string;
  KinesisFirehoseDestination?: KinesisFirehoseDestination;
}
export interface CloudWatchDestination {
  DimensionConfigurations?: DimensionConfiguration[];
}
export interface DimensionConfiguration {
  DimensionValueSource: string;
  DefaultDimensionValue: string;
  DimensionName: string;
}
export interface KinesisFirehoseDestination {
  IAMRoleARN: string;
  DeliveryStreamARN: string;
}
