/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Logs::MetricFilter
 */
export interface AwsLogsMetricfilter {
  Id?: string;
  FilterPattern: string;
  LogGroupName: string;
  MetricTransformations: MetricTransformation[];
}
export interface MetricTransformation {
  DefaultValue?: number;
  MetricName: string;
  MetricNamespace: string;
  MetricValue: string;
}
