/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ElasticLoadBalancingV2::TargetGroup
 */
export interface AwsElasticloadbalancingv2Targetgroup {
  IpAddressType?: string;
  HealthCheckIntervalSeconds?: number;
  LoadBalancerArns?: string[];
  Matcher?: Matcher;
  HealthCheckPath?: string;
  Port?: number;
  Targets?: TargetDescription[];
  HealthCheckEnabled?: boolean;
  ProtocolVersion?: string;
  UnhealthyThresholdCount?: number;
  HealthCheckTimeoutSeconds?: number;
  Name?: string;
  VpcId?: string;
  TargetGroupFullName?: string;
  HealthyThresholdCount?: number;
  HealthCheckProtocol?: string;
  TargetGroupAttributes?: TargetGroupAttribute[];
  TargetType?: string;
  HealthCheckPort?: string;
  Id?: string;
  Protocol?: string;
  TargetGroupName?: string;
  Tags?: Tag[];
}
export interface Matcher {
  GrpcCode?: string;
  HttpCode?: string;
}
export interface TargetDescription {
  AvailabilityZone?: string;
  Id: string;
  Port?: number;
}
export interface TargetGroupAttribute {
  Value?: string;
  Key?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
