/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SageMaker::EndpointConfig
 */
export interface AwsSagemakerEndpointconfig {
  DataCaptureConfig?: DataCaptureConfig;
  ProductionVariants: ProductionVariant[];
  KmsKeyId?: string;
  AsyncInferenceConfig?: AsyncInferenceConfig;
  EndpointConfigName?: string;
  Id?: string;
  Tags?: Tag[];
}
export interface DataCaptureConfig {
  CaptureOptions: CaptureOption[];
  KmsKeyId?: string;
  DestinationS3Uri: string;
  InitialSamplingPercentage: number;
  CaptureContentTypeHeader?: CaptureContentTypeHeader;
  EnableCapture?: boolean;
}
export interface CaptureOption {
  CaptureMode: string;
}
export interface CaptureContentTypeHeader {
  CsvContentTypes?: string[];
  JsonContentTypes?: string[];
}
export interface ProductionVariant {
  ModelName: string;
  VariantName: string;
  InitialInstanceCount?: number;
  ServerlessConfig?: ServerlessConfig;
  InstanceType?: string;
  AcceleratorType?: string;
  InitialVariantWeight: number;
}
export interface ServerlessConfig {
  MaxConcurrency: number;
  MemorySizeInMB: number;
}
export interface AsyncInferenceConfig {
  ClientConfig?: AsyncInferenceClientConfig;
  OutputConfig: AsyncInferenceOutputConfig;
}
export interface AsyncInferenceClientConfig {
  MaxConcurrentInvocationsPerInstance?: number;
}
export interface AsyncInferenceOutputConfig {
  NotificationConfig?: AsyncInferenceNotificationConfig;
  KmsKeyId?: string;
  S3OutputPath: string;
}
export interface AsyncInferenceNotificationConfig {
  SuccessTopic?: string;
  ErrorTopic?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
