/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::Redshift::ClusterParameterGroup
 */
export interface AwsRedshiftClusterparametergroup {
  Id?: string;
  Description: string;
  ParameterGroupFamily: string;
  Parameters?: Parameter[];
  Tags?: Tag[];
}
export interface Parameter {
  ParameterName: string;
  ParameterValue: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
