/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::GuardDuty::Detector
 */
export interface AwsGuarddutyDetector {
  FindingPublishingFrequency?: string;
  Enable: boolean;
  DataSources?: CFNDataSourceConfigurations;
  Id?: string;
}
export interface CFNDataSourceConfigurations {
  S3Logs?: CFNS3LogsConfiguration;
  Kubernetes?: CFNKubernetesConfiguration;
}
export interface CFNS3LogsConfiguration {
  Enable?: boolean;
}
export interface CFNKubernetesConfiguration {
  AuditLogs?: CFNKubernetesAuditLogsConfiguration;
}
export interface CFNKubernetesAuditLogsConfiguration {
  Enable?: boolean;
}
