/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SQS::QueuePolicy
 */
export interface AwsSqsQueuepolicy {
  /**
   * The provider-assigned unique ID for this managed resource.
   */
  Id?: string;
  /**
   * A policy document that contains the permissions for the specified Amazon SQS queues. For more information about Amazon SQS policies, see Creating Custom Policies Using the Access Policy Language in the Amazon Simple Queue Service Developer Guide.
   */
  PolicyDocument:
    | {
        [k: string]: unknown;
      }
    | string;
  /**
   * The URLs of the queues to which you want to add the policy. You can use the Ref function to specify an AWS::SQS::Queue resource.
   */
  Queues: string[];
}
