/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::IAM::InstanceProfile
 */
export interface AwsIamInstanceprofile {
  Path?: string;
  Roles: string[];
  InstanceProfileName?: string;
  Id?: string;
  Arn?: string;
}
