/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::RDS::DBCluster
 */
export interface AwsRdsDbcluster {
  StorageEncrypted?: boolean;
  EndpointPort?: string;
  AssociatedRoles?: DBClusterRole[];
  EnableHttpEndpoint?: boolean;
  EngineMode?: string;
  SnapshotIdentifier?: string;
  Port?: number;
  DBClusterIdentifier?: string;
  PreferredBackupWindow?: string;
  ReadEndpointAddress?: string;
  ReplicationSourceIdentifier?: string;
  VpcSecurityGroupIds?: string[];
  CopyTagsToSnapshot?: boolean;
  GlobalClusterIdentifier?: string;
  RestoreType?: string;
  Engine: string;
  Tags?: Tag[];
  EndpointAddress?: string;
  EngineVersion?: string;
  KmsKeyId?: string;
  AvailabilityZones?: string[];
  DatabaseName?: string;
  PreferredMaintenanceWindow?: string;
  DBSubnetGroupName?: string;
  DeletionProtection?: boolean;
  SourceRegion?: string;
  UseLatestRestorableTime?: boolean;
  MasterUserPassword?: string;
  SourceDBClusterIdentifier?: string;
  MasterUsername?: string;
  ScalingConfiguration?: ScalingConfiguration;
  EnableIAMDatabaseAuthentication?: boolean;
  DBClusterParameterGroupName?: string;
  BackupRetentionPeriod?: number;
  Id?: string;
  BacktrackWindow?: number;
  EnableCloudwatchLogsExports?: string[];
}
export interface DBClusterRole {
  RoleArn: string;
  FeatureName?: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
export interface ScalingConfiguration {
  SecondsUntilAutoPause?: number;
  AutoPause?: boolean;
  MinCapacity?: number;
  MaxCapacity?: number;
}
