/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EC2::Volume
 */
export interface AwsEc2Volume {
  MultiAttachEnabled?: boolean;
  KmsKeyId?: string;
  Encrypted?: boolean;
  Size?: number;
  AutoEnableIO?: boolean;
  OutpostArn?: string;
  AvailabilityZone: string;
  Throughput?: number;
  Iops?: number;
  SnapshotId?: string;
  VolumeType?: string;
  Id?: string;
  Tags?: Tag[];
}
export interface Tag {
  Value: string;
  Key: string;
}
