/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::AppStream::DirectoryConfig
 */
export interface AwsAppstreamDirectoryconfig {
  Id?: string;
  OrganizationalUnitDistinguishedNames: string[];
  ServiceAccountCredentials: ServiceAccountCredentials;
  DirectoryName: string;
}
export interface ServiceAccountCredentials {
  AccountName: string;
  AccountPassword: string;
}
