/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ApiGateway::VpcLink
 */
export interface AwsApigatewayVpclink {
  Description?: string;
  Id?: string;
  TargetArns: string[];
  Tags?: Tag[];
  Name: string;
}
export interface Tag {
  Value: string;
  Key: string;
}
