/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::AutoScaling::ScalingPolicy
 */
export interface AwsAutoscalingScalingpolicy {
  MetricAggregationType?: string;
  PolicyType?: string;
  PredictiveScalingConfiguration?: PredictiveScalingConfiguration;
  ScalingAdjustment?: number;
  Cooldown?: string;
  StepAdjustments?: StepAdjustment[];
  AutoScalingGroupName: string;
  MinAdjustmentMagnitude?: number;
  TargetTrackingConfiguration?: TargetTrackingConfiguration;
  Id?: string;
  EstimatedInstanceWarmup?: number;
  AdjustmentType?: string;
}
export interface PredictiveScalingConfiguration {
  MetricSpecifications: PredictiveScalingMetricSpecification[];
  MaxCapacityBreachBehavior?: string;
  MaxCapacityBuffer?: number;
  SchedulingBufferTime?: number;
  Mode?: string;
}
export interface PredictiveScalingMetricSpecification {
  PredefinedLoadMetricSpecification?: PredictiveScalingPredefinedLoadMetric;
  TargetValue: number;
  PredefinedScalingMetricSpecification?: PredictiveScalingPredefinedScalingMetric;
  PredefinedMetricPairSpecification?: PredictiveScalingPredefinedMetricPair;
}
export interface PredictiveScalingPredefinedLoadMetric {
  ResourceLabel?: string;
  PredefinedMetricType: string;
}
export interface PredictiveScalingPredefinedScalingMetric {
  ResourceLabel?: string;
  PredefinedMetricType: string;
}
export interface PredictiveScalingPredefinedMetricPair {
  ResourceLabel?: string;
  PredefinedMetricType: string;
}
export interface StepAdjustment {
  MetricIntervalUpperBound?: number;
  MetricIntervalLowerBound?: number;
  ScalingAdjustment: number;
}
export interface TargetTrackingConfiguration {
  CustomizedMetricSpecification?: CustomizedMetricSpecification;
  TargetValue: number;
  DisableScaleIn?: boolean;
  PredefinedMetricSpecification?: PredefinedMetricSpecification;
}
export interface CustomizedMetricSpecification {
  MetricName: string;
  Dimensions?: MetricDimension[];
  Statistic: string;
  Unit?: string;
  Namespace: string;
}
export interface MetricDimension {
  Value: string;
  Name: string;
}
export interface PredefinedMetricSpecification {
  ResourceLabel?: string;
  PredefinedMetricType: string;
}
