/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::AppSync::GraphQLApi
 */
export interface AwsAppsyncGraphqlapi {
  OpenIDConnectConfig?: OpenIDConnectConfig;
  Name: string;
  AdditionalAuthenticationProviders?: AdditionalAuthenticationProviders;
  GraphQLUrl?: string;
  LambdaAuthorizerConfig?: LambdaAuthorizerConfig;
  XrayEnabled?: boolean;
  Id?: string;
  Arn?: string;
  UserPoolConfig?: UserPoolConfig;
  ApiId?: string;
  Tags?: Tags;
  AuthenticationType: string;
  LogConfig?: LogConfig;
}
export interface OpenIDConnectConfig {
  ClientId?: string;
  AuthTTL?: number;
  Issuer?: string;
  IatTTL?: number;
}
export interface AdditionalAuthenticationProviders {}
export interface LambdaAuthorizerConfig {
  IdentityValidationExpression?: string;
  AuthorizerUri?: string;
  AuthorizerResultTtlInSeconds?: number;
}
export interface UserPoolConfig {
  AppIdClientRegex?: string;
  UserPoolId?: string;
  AwsRegion?: string;
  DefaultAction?: string;
}
export interface Tags {}
export interface LogConfig {
  ExcludeVerboseContent?: boolean;
  FieldLogLevel?: string;
  CloudWatchLogsRoleArn?: string;
}
