/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The monitoring setting of the component.
 */
export type ComponentMonitoringSetting =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };

/**
 * Resource schema for AWS::ApplicationInsights::Application
 */
export interface AwsApplicationinsightsApplication {
  /**
   * The name of the resource group.
   */
  ResourceGroupName: string;
  /**
   * The ARN of the ApplicationInsights application.
   */
  ApplicationARN?: string;
  /**
   * Indicates whether Application Insights can listen to CloudWatch events for the application resources.
   */
  CWEMonitorEnabled?: boolean;
  /**
   * When set to true, creates opsItems for any problems detected on an application.
   */
  OpsCenterEnabled?: boolean;
  /**
   * The SNS topic provided to Application Insights that is associated to the created opsItem.
   */
  OpsItemSNSTopicArn?: string;
  /**
   * The tags of Application Insights application.
   */
  Tags?: [Tag, ...Tag[]];
  /**
   * The custom grouped components.
   */
  CustomComponents?: [CustomComponent, ...CustomComponent[]];
  /**
   * The log pattern sets.
   */
  LogPatternSets?: [LogPatternSet, ...LogPatternSet[]];
  /**
   * If set to true, application will be configured with recommended monitoring configuration.
   */
  AutoConfigurationEnabled?: boolean;
  /**
   * The monitoring settings of the components.
   */
  ComponentMonitoringSettings?: [ComponentMonitoringSetting, ...ComponentMonitoringSetting[]];
}
/**
 * A key-value pair to associate with a resource.
 */
export interface Tag {
  /**
   * The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   */
  Value: string;
}
/**
 * The custom grouped component.
 */
export interface CustomComponent {
  /**
   * The name of the component.
   */
  ComponentName: string;
  /**
   * The list of resource ARNs that belong to the component.
   */
  ResourceList: [string, ...string[]];
}
/**
 * The log pattern set.
 */
export interface LogPatternSet {
  /**
   * The name of the log pattern set.
   */
  PatternSetName: string;
  /**
   * The log patterns of a set.
   */
  LogPatterns: [LogPattern, ...LogPattern[]];
}
/**
 * The log pattern.
 */
export interface LogPattern {
  /**
   * The name of the log pattern.
   */
  PatternName: string;
  /**
   * The log pattern.
   */
  Pattern: string;
  /**
   * Rank of the log pattern.
   */
  Rank: number;
}
