/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StringFilterList =
  | [StringFilter]
  | [StringFilter, StringFilter]
  | [StringFilter, StringFilter, StringFilter]
  | [StringFilter, StringFilter, StringFilter, StringFilter]
  | [StringFilter, StringFilter, StringFilter, StringFilter, StringFilter]
  | [StringFilter, StringFilter, StringFilter, StringFilter, StringFilter, StringFilter]
  | [StringFilter, StringFilter, StringFilter, StringFilter, StringFilter, StringFilter, StringFilter]
  | [StringFilter, StringFilter, StringFilter, StringFilter, StringFilter, StringFilter, StringFilter, StringFilter]
  | [
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter
    ]
  | [
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter,
      StringFilter
    ];
export type StringComparison = "EQUALS" | "PREFIX" | "NOT_EQUALS";
export type StringInput = string;
export type DateFilterList =
  | [DateFilter]
  | [DateFilter, DateFilter]
  | [DateFilter, DateFilter, DateFilter]
  | [DateFilter, DateFilter, DateFilter, DateFilter]
  | [DateFilter, DateFilter, DateFilter, DateFilter, DateFilter]
  | [DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter]
  | [DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter]
  | [DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter]
  | [DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter, DateFilter]
  | [
      DateFilter,
      DateFilter,
      DateFilter,
      DateFilter,
      DateFilter,
      DateFilter,
      DateFilter,
      DateFilter,
      DateFilter,
      DateFilter
    ];
export type Timestamp = number;
export type NumberFilterList =
  | [NumberFilter]
  | [NumberFilter, NumberFilter]
  | [NumberFilter, NumberFilter, NumberFilter]
  | [NumberFilter, NumberFilter, NumberFilter, NumberFilter]
  | [NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter]
  | [NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter]
  | [NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter]
  | [NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter, NumberFilter]
  | [
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter
    ]
  | [
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter,
      NumberFilter
    ];
export type PortRangeFilterList =
  | [PortRangeFilter]
  | [PortRangeFilter, PortRangeFilter]
  | [PortRangeFilter, PortRangeFilter, PortRangeFilter]
  | [PortRangeFilter, PortRangeFilter, PortRangeFilter, PortRangeFilter]
  | [PortRangeFilter, PortRangeFilter, PortRangeFilter, PortRangeFilter, PortRangeFilter]
  | [PortRangeFilter, PortRangeFilter, PortRangeFilter, PortRangeFilter, PortRangeFilter, PortRangeFilter]
  | [
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter
    ]
  | [
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter
    ]
  | [
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter
    ]
  | [
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter,
      PortRangeFilter
    ];
export type Port = number;
export type MapFilterList =
  | [MapFilter]
  | [MapFilter, MapFilter]
  | [MapFilter, MapFilter, MapFilter]
  | [MapFilter, MapFilter, MapFilter, MapFilter]
  | [MapFilter, MapFilter, MapFilter, MapFilter, MapFilter]
  | [MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter]
  | [MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter]
  | [MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter]
  | [MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter]
  | [MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter, MapFilter];
export type MapComparison = "EQUALS";
export type MapKey = string;
export type MapValue = string;
export type PackageFilterList =
  | [PackageFilter]
  | [PackageFilter, PackageFilter]
  | [PackageFilter, PackageFilter, PackageFilter]
  | [PackageFilter, PackageFilter, PackageFilter, PackageFilter]
  | [PackageFilter, PackageFilter, PackageFilter, PackageFilter, PackageFilter]
  | [PackageFilter, PackageFilter, PackageFilter, PackageFilter, PackageFilter, PackageFilter]
  | [PackageFilter, PackageFilter, PackageFilter, PackageFilter, PackageFilter, PackageFilter, PackageFilter]
  | [
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter
    ]
  | [
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter
    ]
  | [
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter,
      PackageFilter
    ];

/**
 * Inspector Filter resource schema
 */
export interface AwsInspectorv2Filter {
  /**
   * Findings filter name.
   */
  Name: string;
  /**
   * Findings filter description.
   */
  Description?: string;
  /**
   * Findings filter criteria.
   */
  FilterCriteria: {
    AwsAccountId?: StringFilterList;
    ComponentId?: StringFilterList;
    ComponentType?: StringFilterList;
    Ec2InstanceImageId?: StringFilterList;
    Ec2InstanceSubnetId?: StringFilterList;
    Ec2InstanceVpcId?: StringFilterList;
    EcrImageArchitecture?: StringFilterList;
    EcrImageHash?: StringFilterList;
    EcrImageTags?: StringFilterList;
    EcrImagePushedAt?: DateFilterList;
    EcrImageRegistry?: StringFilterList;
    EcrImageRepositoryName?: StringFilterList;
    FindingArn?: StringFilterList;
    FindingStatus?: StringFilterList;
    FindingType?: StringFilterList;
    FirstObservedAt?: DateFilterList;
    InspectorScore?: NumberFilterList;
    LastObservedAt?: DateFilterList;
    NetworkProtocol?: StringFilterList;
    PortRange?: PortRangeFilterList;
    RelatedVulnerabilities?: StringFilterList;
    ResourceId?: StringFilterList;
    ResourceTags?: MapFilterList;
    ResourceType?: StringFilterList;
    Severity?: StringFilterList;
    Title?: StringFilterList;
    UpdatedAt?: DateFilterList;
    VendorSeverity?: StringFilterList;
    VulnerabilityId?: StringFilterList;
    VulnerabilitySource?: StringFilterList;
    VulnerablePackages?: PackageFilterList;
  };
  /**
   * Findings filter action.
   */
  FilterAction: "NONE" | "SUPPRESS";
  /**
   * Findings filter ARN.
   */
  Arn?: string;
}
export interface StringFilter {
  Comparison: StringComparison;
  Value: StringInput;
}
export interface DateFilter {
  EndInclusive?: Timestamp;
  StartInclusive?: Timestamp;
}
export interface NumberFilter {
  LowerInclusive?: number;
  UpperInclusive?: number;
}
export interface PortRangeFilter {
  BeginInclusive?: Port;
  EndInclusive?: Port;
}
export interface MapFilter {
  Comparison: MapComparison;
  Key?: MapKey;
  Value?: MapValue;
}
export interface PackageFilter {
  Architecture?: StringFilter;
  Epoch?: NumberFilter;
  Name?: StringFilter;
  Release?: StringFilter;
  SourceLayerHash?: StringFilter;
  Version?: StringFilter;
}
