/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::ApiGateway::RestApi
 */
export interface AwsApigatewayRestapi {
  Policy?: {
    [k: string]: unknown;
  };
  BodyS3Location?: S3Location;
  Description?: string;
  MinimumCompressionSize?: number;
  Parameters?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "[a-zA-Z0-9]+".
     */
    [k: string]: string;
  };
  CloneFrom?: string;
  Mode?: string;
  DisableExecuteApiEndpoint?: boolean;
  FailOnWarnings?: boolean;
  BinaryMediaTypes?: string[];
  Name?: string;
  RootResourceId?: string;
  ApiKeySourceType?: string;
  EndpointConfiguration?: EndpointConfiguration;
  Id?: string;
  Body?: {
    [k: string]: unknown;
  };
  Tags?: Tag[];
}
export interface S3Location {
  Bucket?: string;
  ETag?: string;
  Version?: string;
  Key?: string;
}
export interface EndpointConfiguration {
  Types?: string[];
  VpcEndpointIds?: string[];
}
export interface Tag {
  Value: string;
  Key: string;
}
