/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::DirectoryService::SimpleAD
 */
export interface AwsDirectoryserviceSimplead {
  Id?: string;
  Alias?: string;
  DnsIpAddresses?: string[];
  CreateAlias?: boolean;
  Description?: string;
  EnableSso?: boolean;
  Name: string;
  Password: string;
  ShortName?: string;
  Size: string;
  VpcSettings: VpcSettings;
}
export interface VpcSettings {
  SubnetIds: string[];
  VpcId: string;
}
