/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::EKS::Nodegroup
 */
export interface AwsEksNodegroup {
  UpdateConfig?: UpdateConfig;
  ScalingConfig?: ScalingConfig;
  Labels?: {
    [k: string]: unknown;
  };
  Taints?: Taint[];
  ReleaseVersion?: string;
  CapacityType?: string;
  NodegroupName?: string;
  Subnets: string[];
  NodeRole: string;
  AmiType?: string;
  ForceUpdateEnabled?: boolean;
  Version?: string;
  LaunchTemplate?: LaunchTemplateSpecification;
  RemoteAccess?: RemoteAccess;
  DiskSize?: number;
  ClusterName: string;
  InstanceTypes?: string[];
  Id?: string;
  Arn?: string;
  Tags?: {
    [k: string]: unknown;
  };
}
export interface UpdateConfig {
  MaxUnavailable?: number;
  MaxUnavailablePercentage?: number;
}
export interface ScalingConfig {
  MinSize?: number;
  DesiredSize?: number;
  MaxSize?: number;
}
export interface Taint {
  Value?: string;
  Effect?: string;
  Key?: string;
}
export interface LaunchTemplateSpecification {
  Id?: string;
  Version?: string;
  Name?: string;
}
export interface RemoteAccess {
  SourceSecurityGroups?: string[];
  Ec2SshKey: string;
}
