/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Resource Type definition for AWS::SageMaker::Workteam
 */
export interface AwsSagemakerWorkteam {
  Id?: string;
  WorkteamName?: string;
  Description?: string;
  NotificationConfiguration?: NotificationConfiguration;
  MemberDefinitions?: MemberDefinition[];
  Tags?: Tag[];
}
export interface NotificationConfiguration {
  NotificationTopicArn: string;
}
export interface MemberDefinition {
  CognitoMemberDefinition: CognitoMemberDefinition;
}
export interface CognitoMemberDefinition {
  CognitoUserPool: string;
  CognitoClientId: string;
  CognitoUserGroup: string;
}
export interface Tag {
  Key: string;
  Value: string;
}
