/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The AWS::GameLift::Alias resource creates an alias for an Amazon GameLift (GameLift) fleet destination.
 */
export interface AwsGameliftAlias {
  /**
   * A human-readable description of the alias.
   */
  Description?: string;
  /**
   * A descriptive label that is associated with an alias. Alias names do not need to be unique.
   */
  Name: string;
  /**
   * A routing configuration that specifies where traffic is directed for this alias, such as to a fleet or to a message.
   */
  RoutingStrategy: {
    [k: string]: unknown;
  };
  /**
   * Unique alias ID
   */
  AliasId?: string;
}
